var React = require('react');
var DelayResizeMixin = require('../mixins/DelayResize.react');

var _animator = false;
var Content = React.createClass({

	statics: {
		// static variable is declared here
		// getAnimator is static variable and can be called by Content.getAnimator()
		getAnimator: function() {
			if(!_animator){
				_animator = document.getElementById('animator');
			}
			return _animator;
		}
	},

	// When components are sharing common functionality, using mixins to recycle code
	// DelayResizeMixin will create windowWidth and windowHeight state and make them update as 
	// two-way binding everytime when window is resized.
	// 
	// Learn more about mixins, check out following link
	// http://facebook.github.io/react/docs/reusable-components.html#mixins
	mixins: [DelayResizeMixin],

	sizingEvent: function() {
		this.ScrollingHandler.forceFireEvent();
	},

	componentDidMount: function() {
		// carry out initial canvas animatin here
		// As ScrollingHandler is using Content component static methods, it needs to be 
		// used when components is mounted.
		// console.log(Content.getAnimator());
		this.ScrollingHandler = require('../actions/ScrollingHandler.js');
		this.ScrollingHandler.initial();
		this.sizingEvent();
	},

	render: function() {
		var s1 = {
			// backgroundColor: 'red'
		};
		var _canvas_style = {
			position: 'fixed',
			top: 0,
			left: 0,
			zIndex: 1,
		};

		return (
			<div>
				<div className='section'>
					<h1 className='title'>React.js playground</h1>
					<h3 className='title'>React.jsのプレーグラウンド</h3>
				</div>
				<div className='section' style={s1}>
					<div className='bottom'>
						<p>Website is structured by many kinds of components. The most fundamental component that usually seen in many website is Header, Aside, Section etc.</p>
						<p>ウェブサイトはたくさんのコンポーネントで構成されたものです。そして、よく使われるコンポーネントはヘッダー、アサイと、セクションなどがあります。</p>
					</div>
				</div>
				<div className='section'>
					<div className='bottom only-large'>
						<p>React.js is working as Virtual DOM. It means HTML code is generated by JavaScript and the most powerful things of React is component can be written in single JS file which contain DOM and script.</p>
						<p>React.jsはVirtual DOMの概念を基づいた作りになっています。すべてのHTMLコードはJavaScriptにより生成されます。そして、これによって、コンポーネントのHTMLパーツとスクリプトパーツは一つのJSファイルにまとめることができます。</p>
					</div>
					<div className='bottom only-small'>
						<p>Component contains JavaScript and HTML can be placed in single JS file.</p>
						<p>JavaScriptとHTMLで構成したコンポーネントは一つJSファイルにまとめることができます。</p>
						<br />
						<br />
						<br />
					</div>
				</div>
				<div className='section'>
					<div className='bottom'>
						<p>So, recycle components in React.js is really a simple things. </p>
						<p>つまり、React.jsを使えば簡単にコンポーネントのリサイクルができます。</p>
					</div>
				</div>

				<canvas id='animator' style={_canvas_style} width={this.state.windowWidth} height={this.state.windowHeight}></canvas>
			</div>
		);
	},

});

module.exports = Content;